version: '3'
services:
  postgreDB:
        image: postgres:10.5
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=online_shope
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5439:5432'
        volumes: 
          - postgres-data:/var/lib/postgresql/data
        networks:
          - backend_network
  products:
      container_name: products
      build: 
        context: .
        dockerfile: ./products/Dockerfile
      command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
      volumes:
        - .:/products
      ports:
        - 8000:8000
      depends_on:
        - postgreDB
      restart: always
      networks:
        - backend_network
volumes:
  postgres-data:

networks:
  backend_network:
