version: '3'
services:
  postgreDB:
        image: postgres:10.5
        restart: always
        environment:
          - POSTGRES_USER=postgre
          - POSTGRES_PASSWORD=postgre
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5439:5432'
        volumes: 
          - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
