version: '3'
services:
  postgreDB:
        container_name: postgreDB
        image: postgres:10.5
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=online_shope
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5439:5432'
        volumes: 
          - postgres-data:/var/lib/postgresql/data
        networks:
          - backend_network
  products:
      container_name: products
      build: 
        context: ./products
        dockerfile: Dockerfile
      command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
      volumes:
        - .:/products
      ports:
        - 8000:8000
      depends_on:
        - postgreDB
      restart: always
      networks:
        - backend_network
  customers:
    container_name: customers
    build:
      context: ./customers
      dockerfile: Dockerfile
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload"
    volumes:
      - .:/customers
    ports:
      - 8001:8001
    depends_on:
      - postgreDB
    restart: always
    networks:
      - backend_network
  orders:
    container_name: orders
    build:
      context: ./orders
      dockerfile: Dockerfile
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload"
    volumes:
      - .:/orders
    ports:
      - 8002:8002
    depends_on:
      - postgreDB
    restart: always
    networks:
      - backend_network
volumes:
  postgres-data:

networks:
  backend_network:
