version: '3'
services:
  postgreDB:
        container_name: postgreDB
        image: postgres:10.5
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=online_shope
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5439:5432'
        volumes: 
          - postgres-data:/var/lib/postgresql/data
        networks:
          - backend_network
  products:
      container_name: products
      build: 
        context: ./products
        dockerfile: Dockerfile
      volumes:
        - .:/products
      ports:
        - 80:80
      depends_on:
        - postgreDB
  customers:
    container_name: customers
    build:
      context: ./customers
      dockerfile: Dockerfile
    volumes:
      - .:/customers
    ports:
      - 80:80
    networks:
      - backend_network
  orders:
    container_name: orders
    build:
      context: ./orders
      dockerfile: Dockerfile
    volumes:
      - .:/orders
    ports:
      - 80:80
    networks:
      - backend_network
  deliveries:
    container_name: deliveries
    build:
      context: ./deliveries
      dockerfile: Dockerfile
    volumes:
      - .:/deliveries
    ports:
      - 80:80
    networks:
      - backend_network
  order_details:
    container_name: order_details
    build:
      context: ./order_details
      dockerfile: Dockerfile
    volumes:
      - .:/order_details
    ports:
      - 80:80
    networks:
      - backend_network
  carts:
    container_name: carts
    build:
      context: ./carts
      dockerfile: Dockerfile
    volumes:
      - .:/carts
    ports:
      - 80:80
    networks:
      - backend_network
volumes:
  postgres-data:

networks:
  backend_network:
